import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "../provider/ReactQueryProvider";
import Sidebar from "./_components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <div className="flex h-screen">
            <Sidebar />
            {children}
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
