import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "../provider/ReactQueryProvider";
import AppLayout from "./_components/AppLayout"; // Import the new AppLayout

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <AppLayout>{children}</AppLayout>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
